FEATURES = [
    "Cycle",
    "Altitude_m",
    "Mach",
    "Tamb_K",
    "Pamb_Pa",
    "RPM_rev_min",
    "FuelFlow_kg_s",
    "P2_Pa",
    "T2_K",
    "P3_Pa",
    "T3_K",
    "P4_Pa",
    "T4_K",
    "CompressorPressureRatio",
    "CompressorTempRise",
    "CombustorPressureLoss",
    "TurbinePressureRatio",
    "TurbineTempDrop",
    "FuelPerRPM",
    "TempRatio_T3_T2",
    "TempRatio_T4_T3",
    "PressureRatio_P3_P2",
    "PressureRatio_P4_P3",
]

TARGETS = [
    "CompressorHealth",
    "CombustorHealth",
    "TurbineHealth",
    "OverallHealth",
    "Thrust_N",
    "TSFC_g_N_s",
]